/**
 * Local filesystem storage abstraction.
 *
 * Every other module (upload parser, ffprobe/ffmpeg services, streaming
 * controller) talks to storage ONLY through this file's functions -- never
 * through raw `fs` calls against a path it built itself, and DB rows never
 * store absolute filesystem paths, only "storage keys" (POSIX-style relative
 * paths under MEDIA_STORAGE_ROOT).
 *
 * This is intentionally shaped so that swapping local disk for an
 * S3-compatible object store later means replacing this one file: callers
 * only ever deal with storage keys + streams, never `path.join` or `fs`
 * directly.
 *
 * The one sanctioned exception is `resolveAbsolutePath()` itself (see its
 * own doc comment below). ffmpeg.service.js, ffprobe.service.js, and
 * waveform.service.js all take absolute filesystem paths, not storage keys
 * or streams -- this is deliberate, not a leak of this module's internals:
 * ffmpeg/ffprobe are native processes invoked via execFile/spawn, and need
 * a real, seekable file on disk for input (and for most outputs -- proxy
 * generation, seek-based thumbnails, filter_complex timeline rendering);
 * there is no stream-based way to hand them an arbitrary file. Every
 * real-world ffmpeg + object-storage integration solves this the same way
 * regardless of language/framework: stage the object to a local temp file,
 * run ffmpeg against that temp file, upload the result back, delete the
 * temp file. That staging step belongs entirely inside this module (a
 * future S3-backed `resolveAbsolutePath()`-equivalent would download to a
 * temp path instead of resolving under STORAGE_ROOT) -- so
 * ffmpeg.service.js and waveform.service.js's absolute-path-based
 * signatures are already the right shape for that swap and are not
 * expected to change when it happens.
 *
 * Layout (all paths are storage keys, relative to STORAGE_ROOT):
 *   <assetId>/original<ext>
 *   <assetId>/proxy.mp4
 *   <assetId>/thumbnail.jpg
 *   <assetId>/waveform.json
 *
 * Keeping every derived asset for a given media asset under one
 * `<assetId>/` directory means deleting a media asset is a single recursive
 * directory removal.
 */

const fs = require("fs");
const fsp = fs.promises;
const path = require("path");
const { STORAGE_ROOT } = require("../config/media");
const { isUuid } = require("../utils/isUuid");

/**
 * Resolve a storage key to an absolute filesystem path, refusing to leave
 * STORAGE_ROOT (path-traversal protection). Storage keys are always
 * generated by this module (never taken verbatim from user input), but this
 * check is a hard backstop regardless.
 *
 * This is the module's one deliberate escape hatch from "callers only deal
 * with storage keys + streams" (see the file header comment): only
 * processing.service.js calls it, and only to hand a real path to the
 * native ffmpeg/ffprobe processes that need one. Nothing else in the app
 * calls this directly or reaches into the filesystem on its own.
 */
function resolveAbsolutePath(storageKey) {
  if (typeof storageKey !== "string" || storageKey.length === 0) {
    throw new Error("storageKey must be a non-empty string");
  }

  const absolute = path.resolve(STORAGE_ROOT, storageKey);
  const rootWithSep = STORAGE_ROOT.endsWith(path.sep)
    ? STORAGE_ROOT
    : STORAGE_ROOT + path.sep;

  if (absolute !== STORAGE_ROOT && !absolute.startsWith(rootWithSep)) {
    throw new Error("Resolved storage path escapes storage root");
  }

  return absolute;
}

function assetDirKey(assetId) {
  return assetId;
}

function originalKey(assetId, extension) {
  const safeExt = extension.startsWith(".") ? extension : `.${extension}`;
  return path.posix.join(assetDirKey(assetId), `original${safeExt}`);
}

function derivedKey(assetId, kind) {
  const filenames = {
    proxy: "proxy.mp4",
    thumbnail: "thumbnail.jpg",
    waveform: "waveform.json",
  };
  const filename = filenames[kind];
  if (!filename) {
    throw new Error(`Unknown derived asset kind: ${kind}`);
  }
  return path.posix.join(assetDirKey(assetId), filename);
}

/**
 * Storage key for a rendered export job's output file, kept under its own
 * top-level `exports/<jobId>/` prefix (siblings of the per-asset
 * `<assetId>/` directories) so export.controller.js's download endpoint can
 * resolve and stream it through the exact same safe, traversal-checked
 * resolveAbsolutePath() path media files already use, instead of the old
 * export.controller.js's unchecked `path.resolve(job.output_file)`.
 */
function exportOutputKey(jobId, format = "mp4") {
  if (!isUuid(jobId)) {
    throw new Error(`Refusing to build an export output key for invalid jobId: ${JSON.stringify(jobId)}`);
  }
  return path.posix.join("exports", jobId, `output.${format}`);
}

async function ensureParentDir(absolutePath) {
  await fsp.mkdir(path.dirname(absolutePath), { recursive: true });
}

/**
 * Pipe a readable stream into storage at `storageKey`. Resolves with bytes
 * written. If `maxBytes` is given and the stream exceeds it, the partial
 * file is removed and the promise rejects with an Error tagged
 * `err.code === "MAX_BYTES_EXCEEDED"`.
 * Resolves once `writeStream` has actually released its file descriptor
 * (the `close` event), or after a short grace period if `close` never
 * fires for some reason. Deleting a file before its write handle is truly
 * closed is unreliable cross-platform -- on Windows in particular, an
 * unlink against a still-open handle can fail outright (the same class of
 * handle-timing issue documented in tests/helpers/testEnv.js), and even on
 * POSIX it's a race rather than a guarantee.
 */
function waitForStreamClose(writeStream) {
  return new Promise((resolveClose) => {
    if (writeStream.closed) {
      resolveClose();
      return;
    }
    let settled = false;
    const done = () => {
      if (settled) return;
      settled = true;
      resolveClose();
    };
    writeStream.once("close", done);
    // Safety net only -- fs write streams always emit 'close' once
    // destroyed/ended, but this guarantees saveStream() can never hang
    // forever if that assumption is ever violated by a future Node version.
    const timer = setTimeout(done, 2000);
    timer.unref?.();
  });
}

/**
 * Pipe a readable stream into storage at `storageKey`. Resolves with bytes
 * written. If `maxBytes` is given and the stream exceeds it, or either
 * stream errors, the partial file is removed and the promise rejects
 * (exceeding `maxBytes` rejects with `err.code === "MAX_BYTES_EXCEEDED"`).
 * Cleanup always waits for the write stream to actually close before
 * unlinking, so it can't lose the race against a still-open file handle.
 */
function saveStream(storageKey, readableStream, maxBytes) {
  const absolutePath = resolveAbsolutePath(storageKey);

  return new Promise((resolve, reject) => {
    ensureParentDir(absolutePath)
      .then(() => {
        const writeStream = fs.createWriteStream(absolutePath);
        let bytesWritten = 0;
        let aborted = false;

        function cleanupAndReject(err) {
          if (aborted) return;
          aborted = true;

          readableStream.unpipe(writeStream);
          readableStream.destroy();

          const closed = waitForStreamClose(writeStream);
          writeStream.destroy();

          closed
            .then(() => fsp.unlink(absolutePath))
            .catch((unlinkErr) => {
              if (unlinkErr && unlinkErr.code !== "ENOENT") {
                // Don't silently leave a partial file unaccounted for --
                // this is the failure case the cleanup itself can't fix.
                console.error(
                  `[storage] failed to remove partial upload at ${absolutePath}: ${unlinkErr.message}`
                );
              }
            })
            .then(() => reject(err));
        }

        readableStream.on("data", (chunk) => {
          bytesWritten += chunk.length;
          if (typeof maxBytes === "number" && bytesWritten > maxBytes && !aborted) {
            const err = new Error(`Stream exceeded maxBytes (${maxBytes})`);
            err.code = "MAX_BYTES_EXCEEDED";
            cleanupAndReject(err);
          }
        });

        readableStream.on("error", (err) => {
          cleanupAndReject(err);
        });

        writeStream.on("error", (err) => {
          cleanupAndReject(err);
        });

        writeStream.on("finish", () => {
          if (!aborted) resolve({ bytesWritten, absolutePath });
        });

        readableStream.pipe(writeStream);
      })
      .catch(reject);
  });
}

function createReadStream(storageKey, options) {
  const absolutePath = resolveAbsolutePath(storageKey);
  return fs.createReadStream(absolutePath, options);
}

async function exists(storageKey) {
  try {
    await fsp.access(resolveAbsolutePath(storageKey));
    return true;
  } catch {
    return false;
  }
}

async function stat(storageKey) {
  return fsp.stat(resolveAbsolutePath(storageKey));
}

/**
 * Remove the entire directory for a media asset (original + all derived
 * assets). This is a recursive `rm`, so it must never be trusted to run
 * against anything other than a genuine per-asset subdirectory -- it does
 * NOT rely solely on callers having already validated `assetId` (every
 * current caller does, via isUuid() upstream, but this function is
 * documented as a security boundary in its own right and must hold that
 * guarantee independently).
 *
 * In particular, `resolveAbsolutePath(".")` resolves to STORAGE_ROOT itself
 * (it doesn't "escape" the root, it *is* the root) and would otherwise pass
 * the traversal check in resolveAbsolutePath() -- so an assetId of "."
 * would delete the entire storage root. Requiring a real UUID closes that
 * and every other unsafe value (empty string, "..", path separators) in
 * one check, since assetId is a UUID for every asset that will ever exist.
 */
async function deleteAssetDirectory(assetId) {
  if (!isUuid(assetId)) {
    throw new Error(`Refusing to delete asset directory for invalid assetId: ${JSON.stringify(assetId)}`);
  }

  const absolutePath = resolveAbsolutePath(assetDirKey(assetId));
  await fsp.rm(absolutePath, { recursive: true, force: true });
}

/** Remove a single derived/original file by its storage key (not recursive -- use deleteAssetDirectory to remove a whole asset). */
async function deleteKey(storageKey) {
  const absolutePath = resolveAbsolutePath(storageKey);
  await fsp.rm(absolutePath, { force: true });
}

module.exports = {
  STORAGE_ROOT,
  resolveAbsolutePath,
  originalKey,
  derivedKey,
  exportOutputKey,
  ensureParentDir,
  saveStream,
  createReadStream,
  exists,
  stat,
  deleteAssetDirectory,
  deleteKey,
};
